/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as KeinZugangRouteImport } from './routes/kein-zugang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBewerbungenRouteImport } from './routes/_app/bewerbungen'
import { Route as AppMitgliederRouteImport } from './routes/_app/mitglieder'
import { Route as AppOffboardingRouteImport } from './routes/_app/offboarding'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMockRouteImport } from './routes/api/auth/mock'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const KeinZugangRoute = KeinZugangRouteImport.update({
  id: '/kein-zugang',
  path: '/kein-zugang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBewerbungenRoute = AppBewerbungenRouteImport.update({
  id: '/bewerbungen',
  path: '/bewerbungen',
  getParentRoute: () => AppRoute,
} as any)
const AppMitgliederRoute = AppMitgliederRouteImport.update({
  id: '/mitglieder',
  path: '/mitglieder',
  getParentRoute: () => AppRoute,
} as any)
const AppOffboardingRoute = AppOffboardingRouteImport.update({
  id: '/offboarding',
  path: '/offboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMockRoute = ApiAuthMockRouteImport.update({
  id: '/api/auth/mock',
  path: '/api/auth/mock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/kein-zugang': typeof KeinZugangRoute
  '/login': typeof LoginRoute
  '/bewerbungen': typeof AppBewerbungenRoute
  '/mitglieder': typeof AppMitgliederRoute
  '/offboarding': typeof AppOffboardingRoute
  '/onboarding': typeof AppOnboardingRoute
  '/scanner': typeof AppScannerRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mock': typeof ApiAuthMockRoute
}
export interface FileRoutesByTo {
  '/kein-zugang': typeof KeinZugangRoute
  '/login': typeof LoginRoute
  '/bewerbungen': typeof AppBewerbungenRoute
  '/mitglieder': typeof AppMitgliederRoute
  '/offboarding': typeof AppOffboardingRoute
  '/onboarding': typeof AppOnboardingRoute
  '/scanner': typeof AppScannerRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mock': typeof ApiAuthMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/kein-zugang': typeof KeinZugangRoute
  '/login': typeof LoginRoute
  '/_app/bewerbungen': typeof AppBewerbungenRoute
  '/_app/mitglieder': typeof AppMitgliederRoute
  '/_app/offboarding': typeof AppOffboardingRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/scanner': typeof AppScannerRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/mock': typeof ApiAuthMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kein-zugang'
    | '/login'
    | '/bewerbungen'
    | '/mitglieder'
    | '/offboarding'
    | '/onboarding'
    | '/scanner'
    | '/api/health'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/mock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/kein-zugang'
    | '/login'
    | '/bewerbungen'
    | '/mitglieder'
    | '/offboarding'
    | '/onboarding'
    | '/scanner'
    | '/api/health'
    | '/'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/mock'
  id:
    | '__root__'
    | '/_app'
    | '/kein-zugang'
    | '/login'
    | '/_app/bewerbungen'
    | '/_app/mitglieder'
    | '/_app/offboarding'
    | '/_app/onboarding'
    | '/_app/scanner'
    | '/api/health'
    | '/_app/'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  KeinZugangRoute: typeof KeinZugangRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMockRoute: typeof ApiAuthMockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kein-zugang': {
      id: '/kein-zugang'
      path: '/kein-zugang'
      fullPath: '/kein-zugang'
      preLoaderRoute: typeof KeinZugangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bewerbungen': {
      id: '/_app/bewerbungen'
      path: '/bewerbungen'
      fullPath: '/bewerbungen'
      preLoaderRoute: typeof AppBewerbungenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mitglieder': {
      id: '/_app/mitglieder'
      path: '/mitglieder'
      fullPath: '/mitglieder'
      preLoaderRoute: typeof AppMitgliederRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offboarding': {
      id: '/_app/offboarding'
      path: '/offboarding'
      fullPath: '/offboarding'
      preLoaderRoute: typeof AppOffboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/mock': {
      id: '/api/auth/mock'
      path: '/api/auth/mock'
      fullPath: '/api/auth/mock'
      preLoaderRoute: typeof ApiAuthMockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBewerbungenRoute: typeof AppBewerbungenRoute
  AppMitgliederRoute: typeof AppMitgliederRoute
  AppOffboardingRoute: typeof AppOffboardingRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppScannerRoute: typeof AppScannerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBewerbungenRoute: AppBewerbungenRoute,
  AppMitgliederRoute: AppMitgliederRoute,
  AppOffboardingRoute: AppOffboardingRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppScannerRoute: AppScannerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  KeinZugangRoute: KeinZugangRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMockRoute: ApiAuthMockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
